### ISSUE TITLE
Problems pushing from Rstudio

### ISSUE THREAD

**Issue by vicmarza** [STAT540-UBC/STAT540-UBC.github.io#12]
Hello all,

I'm having an issue when pushing changes to my repo from Rstudio. I am able to commit changes; however, when I try to push, I get the following error

`remote: error: GH001: Large files detected. You may want to try Git Large File Storage-https://git-lfs.github.com.
remote: error: Trace: c57148b5a6d91da91643dffe09882f16
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Seminars/Seminar 7/methyl_ALL.Rdata is 145.77 MB; this exceeds GitHub's file size limit of 100.00 MB
To github.com:STAT540-UBC/zz_martinez-victor_STAT540_2018.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@github.com:STAT540-UBC/zz_martinez-victor_STAT540_2018.git'`

I initially forgot to ignore the huge `methyl_ALL.Rdata` file (seminar 7). I deleted the file, ignore it from commits, etc., but I keep getting the error above. I even tried the Git Large File Storage" solution mentioned, with no success.  

No changes are made to my repo

Do you have any suggestion?

Thanks!

Victor

@STAT540-UBC/ta_2018

**Comment by oganm** [comment]
Please see https://stackoverflow.com/questions/927358/how-to-undo-the-most-recent-commits-in-git and/or https://help.github.com/articles/removing-files-from-a-repository-s-history/
