### ISSUE TITLE
Problem with Push (SOLVED!)

### ISSUE THREAD

**Issue by sambreaux** [STAT540-UBC/STAT540-UBC.github.io#18]
hi i know a lot of people had problems with this step so hopefully this will hep someone C:
for me it was a problem with the ssh key (and also why i couldn't create a new project with the ssh path) 

1st if you made a password delete it using "$ ssh-keygen -p" in git bash and just press through enter
(alternatively you can make a new key) 

2nd make sure your ssh connection is working
(in git bash) 
"$ ssh -T git@github.com"
if you get a return like 
"The authenticity of host 'github.com (IP ADDRESS)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)?" 
its not connected
type in "yes" and press enter

and then it should work!

**Comment by thiombane** [comment]
Hey @sambreaux,
Thank you for sharing. It unfortunately did not work for my case. Does anyone else have another potential solution for this issue?

**Comment by jafarzadeh91** [comment]
thanks @sambreaux . @thiombane Can you explain the error you get in more detail if it still persists?
