### ISSUE TITLE
Lecture 7 uploaded but link is not working

### ISSUE THREAD

**Issue by gcohenfr** [STAT540-UBC/STAT540-UBC.github.io#19]

**Comment by jafarzadeh91** [comment]
Hi Gabby,
If you have access to the repository you should knit the lectures. Rmd. This process updates the lectures.html file. Then you should push the lectures.html file to the Github repository.

**Comment by jafarzadeh91** [comment]
If you have difficulties in this process, I can perform it too.

**Comment by gcohenfr** [comment]
Please, knit and push if you haven’t done it already. 
Thanks 

Gaby
