### ISSUE TITLE
Data set for Question 4

### ISSUE THREAD

**Issue by tanjahoegg** [STAT540-UBC/STAT540-UBC.github.io#2]
Hi, 

I'm just working on the assignment and it seems that the link to the data set in Question 4a. isn't working (I also can't find the data in the usual folders). Is it available yet?

Thanks!

**Comment by AlisonMcAfee** [comment]
Yes, please make it available. I know you said you would today.

Cheers

**Comment by gcohenfr** [comment]
DONE! the dataset for Q4 is now in the repository. All datasets for hw02 are in  `examples/yeastPlatforms/data`
